// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Carniceria.DAL;

#nullable disable

namespace Proyecto_Carniceria.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Data.Models.CarritoDeCompras", b =>
                {
                    b.Property<int>("CarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Compra")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MontoTotal")
                        .HasColumnType("REAL");

                    b.HasKey("CarritoId");

                    b.ToTable("CarritoDeCompras");
                });

            modelBuilder.Entity("Data.Models.CategoriaCarnes", b =>
                {
                    b.Property<int>("CategoriaCarnesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaCarnesId");

                    b.ToTable("CategoriaCarnes");
                });

            modelBuilder.Entity("Data.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Data.Models.DetalleProductos", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarritoDeComprasCarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PedidosPedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Productos")
                        .HasColumnType("TEXT");

                    b.Property<float>("precio")
                        .HasColumnType("REAL");

                    b.HasKey("DetalleId");

                    b.HasIndex("CarritoDeComprasCarritoId");

                    b.HasIndex("PedidosPedidoId");

                    b.ToTable("DetalleProductos");
                });

            modelBuilder.Entity("Data.Models.Detalles_Pagos", b =>
                {
                    b.Property<int>("DetallePagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetodosPagosMetodoPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MontoPagado")
                        .HasColumnType("REAL");

                    b.Property<int>("PagoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PagosPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PedidosPedidoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetallePagoId");

                    b.HasIndex("MetodosPagosMetodoPagoId");

                    b.HasIndex("PagosPagoId");

                    b.HasIndex("PedidosPedidoId");

                    b.ToTable("Detalles_Pagos");
                });

            modelBuilder.Entity("Data.Models.Estadisticas", b =>
                {
                    b.Property<int>("EstadisticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<float>("IngresosTotales")
                        .HasColumnType("REAL");

                    b.Property<int>("PedidosHoy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalClientes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPagos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPedidos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalProductos")
                        .HasColumnType("INTEGER");

                    b.Property<float>("VentasHoy")
                        .HasColumnType("REAL");

                    b.HasKey("EstadisticaId");

                    b.ToTable("Estadisticas");
                });

            modelBuilder.Entity("Data.Models.Estados", b =>
                {
                    b.Property<int>("EstadosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("EstadosId");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Data.Models.MetodosPagos", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodosPagos");
                });

            modelBuilder.Entity("Data.Models.Pagos", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClienteId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<float>("MontoPagado")
                        .HasColumnType("REAL");

                    b.HasKey("PagoId");

                    b.HasIndex("ClienteId1");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Data.Models.Pedidos", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Entrega")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstadosId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MontoTotal")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Recibido")
                        .HasColumnType("TEXT");

                    b.HasKey("PedidoId");

                    b.HasIndex("EstadosId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Data.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaCarneId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaCarnesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<float>("CostoLibra")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenProducto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<float>("PrecioLibra")
                        .HasColumnType("REAL");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaCarnesId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Data.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmacionContrasena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Data.Models.DetalleProductos", b =>
                {
                    b.HasOne("Data.Models.CarritoDeCompras", null)
                        .WithMany("Productos")
                        .HasForeignKey("CarritoDeComprasCarritoId");

                    b.HasOne("Data.Models.Pedidos", null)
                        .WithMany("productosOrdenados")
                        .HasForeignKey("PedidosPedidoId");
                });

            modelBuilder.Entity("Data.Models.Detalles_Pagos", b =>
                {
                    b.HasOne("Data.Models.MetodosPagos", "MetodosPagos")
                        .WithMany()
                        .HasForeignKey("MetodosPagosMetodoPagoId");

                    b.HasOne("Data.Models.Pagos", "Pagos")
                        .WithMany("DetallesPagos")
                        .HasForeignKey("PagosPagoId");

                    b.HasOne("Data.Models.Pedidos", "Pedidos")
                        .WithMany()
                        .HasForeignKey("PedidosPedidoId");

                    b.Navigation("MetodosPagos");

                    b.Navigation("Pagos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Data.Models.Pagos", b =>
                {
                    b.HasOne("Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId1");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Data.Models.Pedidos", b =>
                {
                    b.HasOne("Data.Models.Estados", "Estados")
                        .WithMany()
                        .HasForeignKey("EstadosId");

                    b.Navigation("Estados");
                });

            modelBuilder.Entity("Data.Models.Productos", b =>
                {
                    b.HasOne("Data.Models.CategoriaCarnes", "CategoriaCarnes")
                        .WithMany()
                        .HasForeignKey("CategoriaCarnesId");

                    b.Navigation("CategoriaCarnes");
                });

            modelBuilder.Entity("Data.Models.CarritoDeCompras", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Data.Models.Pagos", b =>
                {
                    b.Navigation("DetallesPagos");
                });

            modelBuilder.Entity("Data.Models.Pedidos", b =>
                {
                    b.Navigation("productosOrdenados");
                });
#pragma warning restore 612, 618
        }
    }
}
